name: Deploy Docusaurus

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [confidential-update]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório público
      uses: actions/checkout@v3

    - name: Clonar o repositório confidencial em pasta temporária
      run: |
        git clone https://x-access-token:${{ secrets.CONFIDENTIAL_REPO_TOKEN }}@github.com/ppsa-sgpp/sgpp-tech-guide-confidential.git confidential-docs

    - name: Mover arquivos confidenciais para a pasta docs
      run: |
        cp -r confidential-docs/* docs/+confidential
        rm -rf confidential-docs

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Instalar dependências
      run: npm ci

    - name: Build do site
      run: npm run build

    - name: Deploy para GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
