name: Deploy Docusaurus

on:
  push:
    branches:
      - main  # Publicar sempre que houver um push no branch `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # Verifique a versão do Node suportada pelo seu projeto

    - name: Instalar dependências
      run: npm ci

    - name: Build do site
      run: npm run build

    - name: Deploy para GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
